version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" # Only expose if you need to access from host directly
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env

  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Specify the Dockerfile explicitly
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db  # Use the service name for internal DNS resolution
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: production # or development for dev mode
    networks:
      - app_network
    volumes:
      - ./backend/uploads:/usr/src/app/uploads # Only mount uploads directory
    # No need to mount the entire backend directory unless for active development
    command: npm run start:prod # or npm run start:dev for development
    env_file:
      - ./backend/.env

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Specify the Dockerfile explicitly
    container_name: react_app
    ports:
      - "80:80" # Use standard port 80
    networks:
      - app_network
    depends_on:
      - nestjs-app
    # No need to mount the entire frontend directory, the build artifacts are copied
    # volumes:
    #   - ./frontend:/usr/share/nginx/html
    # Remove the React app container, it is served by Nginx
    # command: ["nginx", "-g", "daemon off;"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Your Nginx config
      - react_build:/usr/share/nginx/html  # Mount the React build directory
    depends_on:
      - react-app # Nginx depends on the React app being built
      - nestjs-app
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
  react_build: # Define a volume for the React build

networks:
  app_network:
    driver: bridge