version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env  # Use the root .env file for database variables

  nestjs-app:
    build:
      context: ./backend  # Path to your NestJS app
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    networks:
      - app_network
    volumes:
      - ./backend:/usr/src/app  # Mount backend directory
      - ./backend/uploads:/usr/src/app/uploads
    working_dir: /usr/src/app
    command: npm run start:dev
    env_file:
      - ./backend/.env  # Reference the .env inside the backend directory

  react-app:
    build:
      context: ./frontend  # Path to your React app
    container_name: react_app
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - nestjs-app
    volumes:
      - ./frontend:/usr/share/nginx/html  # Serve React app using Nginx
    command: ["nginx", "-g", "daemon off;"]  # This will run Nginx to serve the app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html  # Serve React app
    depends_on:
      - react-app
      - nestjs-app
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]  # Keep Nginx running

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
