version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env  # Use the root .env file for database variables

  nestjs-app:
    build:
      context: ./backend  # Path to your NestJS app
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    networks:
      - app_network
    volumes:
      - ./backend:/usr/src/app  # Mount backend directory
      - ./backend/uploads:/usr/src/app/uploads  # Mount uploads folder for persistent data
    working_dir: /usr/src/app
    command: npm run start:dev  # Development mode (you can change it if needed)
    env_file:
      - ./backend/.env  # Reference the .env inside the backend directory

  react-app:
    build:
      context: ./frontend  # Path to your frontend (React app)
    container_name: react_app
    ports:
      - "8080:80"  # Nginx serves React on port 80, but mapped to 8080 on host
    networks:
      - app_network
    depends_on:
      - nestjs-app
    volumes:
      - ./frontend:/usr/share/nginx/html  # Mount frontend code (for development)
    command: ["nginx", "-g", "daemon off;"]  # Nginx to serve the app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Nginx mapped to 80 on host for production use
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ./frontend:/usr/share/nginx/html  # Serve React from Nginx
    depends_on:
      - react-app
      - nestjs-app
    networks:
      - app_network
    restart: always  # Ensures Nginx restarts on reboot
    command: ["nginx", "-g", "daemon off;"]  # Keep Nginx running in the foreground

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
