version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" # Expose for local access (optional)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env

  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db  # Internal service name for DB
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: production
    networks:
      - app_network
    volumes:
      - ./backend/uploads:/usr/src/app/uploads # Mount only necessary folders
    command: npm run start:prod # Start in production mode
    env_file:
      - ./backend/.env

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile   # Ensure it's pointing to the correct Dockerfile
    ports:
      - "8080:80"  # Exposing the Nginx port for frontend access
    depends_on:
      - nestjs-app  # In case you have a dependency on the NestJS backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"  # Expose port 80 for React app through Nginx
      - "8443:443" # Expose port 443 for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html # React build output directory
      - ./nginx/ssl:/etc/nginx/ssl # SSL certificates
    depends_on:
      - react-app # Nginx depends on React build being available
      - nestjs-app
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
  react_build:  # Persistent volume for the React build output
  nginx_ssl: 
    external: true  # Make sure your SSL certificates are available

networks:
  app_network:
    driver: bridge
